### ISSUE TITLE
Rotate service logs instead of overwriting them

### ISSUE THREAD

**Issue by jvansanten** [AmpelProject/singularity-stack#12]
Service logfiles get overwritten every time the nanny process restarts. While this is similar to how Docker works, it is probably not what we want.

**Comment by vbrinnel** [comment]
singularity-stack logs burst mongo | less
```
Traceback (most recent call last):
  File "/scratch/jvs/miniconda3/envs/singularity-stack/bin/singularity-stack", line 11, in <module>
    load_entry_point('singularity-stack', 'console_scripts', 'singularity-stack')()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/scratch/jvs/singularity-stack/singularity_stack.py", line 246, in <module>
    class LogRotator(logging.TimedRotatingLogHandler):
AttributeError: module 'logging' has no attribute 'TimedRotatingLogHandler'
```
