### ISSUE TITLE
Impossible to deploy because of missing module

### ISSUE THREAD

**Issue by vbrinnel** [AmpelProject/singularity-stack#14]
Cannot use deploy anymore:

```
(singularity-stack) [burst] /home/ampel/dryrun > ../Ampel-v0.5/ampel-deploy/up dryrun replay_archive

Traceback (most recent call last):
  File "/scratch/jvs/miniconda3/envs/singularity-stack/bin/singularity-stack", line 11, in <module>
    load_entry_point('singularity-stack', 'console_scripts', 'singularity-stack')()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/scratch/jvs/singularity-stack/singularity_stack.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/scratch/jvs/miniconda3/envs/singularity-stack/bin/singularity-stack", line 11, in <module>
    load_entry_point('singularity-stack', 'console_scripts', 'singularity-stack')()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/scratch/jvs/singularity-stack/singularity_stack.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/scratch/jvs/miniconda3/envs/singularity-stack/bin/singularity-stack", line 11, in <module>
    load_entry_point('singularity-stack', 'console_scripts', 'singularity-stack')()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/scratch/jvs/singularity-stack/singularity_stack.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Impossible to fix the situation with the ampel user:
```
(singularity-stack) [burst] /home/ampel/dryrun > pip install requests

Collecting requests
  Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 1.1MB/s 
Collecting idna<2.8,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 1.9MB/s 
Requirement already satisfied: certifi>=2017.4.17 in /scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages (from requests)
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.6MB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests)
  Downloading https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 5.2MB/s 
Installing collected packages: idna, chardet, urllib3, requests
Exception:
Traceback (most recent call last):
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/wheel.py", line 352, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/jvs/miniconda3/envs/singularity-stack/lib/python3.6/site-packages/idna'
```

**Comment by vbrinnel** [comment]
Workaround:
```
pip install --user requests 
```

**Comment by jvansanten** [comment]
Fixed by installing requests in environment. Removed ~ampel/.local to preserve environment isolation.
